# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\"+\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\")\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\"\x1e\n\x0bPingRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\"0\n\tPingReply\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x12\n\nelapsed_ms\x18\x02 \x01(\x01\x32\xa3\x01\n\x0b\x45\x63hoService\x12\x30\n\x08SayHello\x12\x12.echo.HelloRequest\x1a\x10.echo.HelloReply\x12*\n\x04Ping\x12\x11.echo.PingRequest\x1a\x0f.echo.PingReply\x12\x36\n\x0cServerStream\x12\x12.echo.HelloRequest\x1a\x10.echo.HelloReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=20
  _globals['_HELLOREQUEST']._serialized_end=63
  _globals['_HELLOREPLY']._serialized_start=65
  _globals['_HELLOREPLY']._serialized_end=106
  _globals['_PINGREQUEST']._serialized_start=108
  _globals['_PINGREQUEST']._serialized_end=138
  _globals['_PINGREPLY']._serialized_start=140
  _globals['_PINGREPLY']._serialized_end=188
  _globals['_ECHOSERVICE']._serialized_start=191
  _globals['_ECHOSERVICE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
